name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker-practice/actions-setup-docker@master
        with:
          docker_version: 27.2
      - run: bash ./test.sh
